### ISSUE TITLE
ssl_verify_peer_cert not found.

### ISSUE THREAD

**Issue by sahad752** [NVISOsecurity/disable-flutter-tls-verification#18]
When running the Android Emulator with a Flutter application, I encountered the following error message:

```
Spawned `----------`. Resuming main thread!                     
[Android Emulator 5554::-----------]-> [+] Flutter library found
[!] ssl_verify_peer_cert not found. Please open an issue at https://github.com/NVISOsecurity/disable-flutter-tls-verification/issues
[+] Match pattern: F? 0F 1C F8 F? 5? 01 A9 F? 5? 02 A9 F? ?? 03 A9 ?? ?? ?? ?? 68 1A 40 F9
[+] ssl_verify_result found at: 0x6d346133e8
[+] ssl_verify_peer_cert found at offset: 0x3a23e8
[+] Hook success!
[+] Done
[+] Done                                                                                                                                      
[+] Done
```
On android studio i got following error 
```
Exception occurred: DioException [bad certificate]: The certificate of the response is not approved.
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  Error: Instance of '_X509CertificateImpl' stackTrace: #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #1      _rootRunUnary (dart:async/zone.dart:1434)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #2      _CustomZone.runUnary (dart:async/zone.dart:1335)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #3      _FutureListener.handleError (dart:async/future_impl.dart:165)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #5      Future._propagateToListeners (dart:async/future_impl.dart:799)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #6      Future._completeError (dart:async/future_impl.dart:574)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #7      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #8      _Completer.completeError (dart:async/future_impl.dart:23)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #9      Future.any.onError (dart:async/future.dart:616)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #10     _rootRunBinary (dart:async/zone.dart:1450)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #11     _CustomZone.runBinary (dart:async/zone.dart:1342)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #12     _FutureListener.handleError (dart:async/future_impl.dart:162)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #14     Future._propagateToListeners (dart:async/future_impl.dart:799)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #15     Future._completeError (dart:async/future_impl.dart:574)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #16     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:519)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #17     _rootRun (dart:async/zone.dart:1426)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #18     _CustomZone.run (dart:async/zone.dart:1328)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #19     _CustomZone.runGuarded (dart:async/zone.dart:1236)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
2023-11-04 07:28:07.893  6232-6321  flutter                 com.app.id                   I  #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

```
Test app works fine
<img width="317" alt="Screenshot 2023-11-04 at 7 41 59 AM" src="https://github.com/NVISOsecurity/disable-flutter-tls-verification/assets/20284850/9251b75c-5e58-4d00-9922-88161e33a9c4">

**Comment by rahulr311295** [comment]
Try patching your apk file using objection and then run the script

**Comment by sahad752** [comment]
Thanks @rahulr311295 ,will try
